import { createTheme, createThemeContract } from '@vanilla-extract/css';

export const tokens = createThemeContract({
  colors: {
    primitive: {
      light: null,
      dark: null,
      glow: null,
      base: null,
      strong: null,
      accent: null,
      accentDark: null,
      accentLight: null,
      destructive: null,
    },
    semantic: {
      background: null,
      foreground: null,
      primary: null,
      primaryForeground: null,
      secondary: null,
      secondaryForeground: null,
      muted: null,
      mutedForeground: null,
      accent: null,
      accentForeground: null,
      destructive: null,
      destructiveForeground: null,
      border: null,
      input: null,
      ring: null,
      card: null,
      cardForeground: null,
      popover: null,
      popoverForeground: null,
    },
  },
  spacing: {
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    '3xl': null,
    '4xl': null,
  },
  typography: {
    fontSize: {
      xs: null,
      sm: null,
      base: null,
      lg: null,
      xl: null,
      '2xl': null,
      '3xl': null,
      '4xl': null,
      '5xl': null,
      '6xl': null,
      '7xl': null,
    },
    fontWeight: {
      normal: null,
      medium: null,
      semibold: null,
      bold: null,
    },
    lineHeight: {
      tight: null,
      snug: null,
      normal: null,
      relaxed: null,
      loose: null,
    },
  },
  borderRadius: {
    none: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    full: null,
  },
  shadows: {
    sm: null,
    md: null,
    lg: null,
    xl: null,
  },
  breakpoints: {
    sm: null,
    md: null,
    lg: null,
    xl: null,
  },
});

const primitiveColors = {
  light: 'hsl(266, 78%, 93%)',
  dark: 'hsl(282, 100%, 16%)',
  glow: 'hsl(280, 100%, 70%)',
  base: 'hsl(270, 100%, 60%)',
  strong: 'hsl(266, 78%, 45%)',
  accent: 'hsl(192, 65%, 72%)',
  accentDark: 'hsl(192, 50%, 35%)',
  accentLight: 'hsl(192, 50%, 90%)',
  destructive: 'hsl(5, 100%, 71%)',
};

export const lightTokens = createTheme(tokens, {
  colors: {
    primitive: primitiveColors,
    semantic: {
      background: 'transparent',
      foreground: primitiveColors.dark,
      primary: primitiveColors.dark,
      primaryForeground: primitiveColors.light,
      secondary: primitiveColors.light,
      secondaryForeground: primitiveColors.dark,
      muted: 'hsl(210 40% 96%)',
      mutedForeground: 'hsl(215.4 16.3% 46.9%)',
      accent: primitiveColors.accent,
      accentForeground: primitiveColors.dark,
      destructive: primitiveColors.destructive,
      destructiveForeground: primitiveColors.light,
      border: primitiveColors.dark,
      input: primitiveColors.dark,
      ring: primitiveColors.dark,
      card: 'transparent',
      cardForeground: primitiveColors.dark,
      popover: 'transparent',
      popoverForeground: primitiveColors.dark,
    },
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
    '4xl': '6rem',
  },
  typography: {
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '3.75rem',
      '7xl': '4.5rem',
    },
    fontWeight: {
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
    lineHeight: {
      tight: '1.25',
      snug: '1.375',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2',
    },
  },
  borderRadius: {
    none: '0',
    sm: '0.125rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
  },
});

export const darkTokens = createTheme(tokens, {
  colors: {
    primitive: primitiveColors,
    semantic: {
      background: 'transparent',
      foreground: primitiveColors.light,
      primary: primitiveColors.light,
      primaryForeground: primitiveColors.dark,
      secondary: primitiveColors.dark,
      secondaryForeground: primitiveColors.light,
      muted: primitiveColors.dark,
      mutedForeground: 'hsl(215 20.287% 65.1%)',
      accent: primitiveColors.accentDark,
      accentForeground: primitiveColors.accentLight,
      destructive: primitiveColors.destructive,
      destructiveForeground: primitiveColors.accentLight,
      border: primitiveColors.accentDark,
      input: 'hsl(217.2 32.6% 17.5%)',
      ring: 'hsl(212.7 26.8% 83.9%)',
      card: 'hsl(222.2 84% 4.9%)',
      cardForeground: 'hsl(210 40% 98%)',
      popover: 'hsl(222.2 84% 4.9%)',
      popoverForeground: 'hsl(210 40% 98%)',
    },
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
    '4xl': '6rem',
  },
  typography: {
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '3.75rem',
      '7xl': '4.5rem',
    },
    fontWeight: {
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
    lineHeight: {
      tight: '1.25',
      snug: '1.375',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2',
    },
  },
  borderRadius: {
    none: '0',
    sm: '0.125rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
  },
});
