import { createTheme, createThemeContract } from '@vanilla-extract/css';

export const vars = createThemeContract({
  color: {
    background: null,
    foreground: null,
    primary: null,
    primaryForeground: null,
    secondary: null,
    secondaryForeground: null,
    muted: null,
    mutedForeground: null,
    accent: null,
    accentForeground: null,
    destructive: null,
    destructiveForeground: null,
    border: null,
    input: null,
    ring: null,
    card: null,
    cardForeground: null,
    popover: null,
    popoverForeground: null,
  },
  spacing: {
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    '3xl': null,
    '4xl': null,
  },
  fontSize: {
    xs: null,
    sm: null,
    base: null,
    lg: null,
    xl: null,
    '2xl': null,
    '3xl': null,
    '4xl': null,
    '5xl': null,
    '6xl': null,
    '7xl': null,
  },
  radius: {
    none: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    full: null,
  },
});

const colorPalette: Record<string, string> = {
  light: 'hsl(266, 78%, 93%)',
  dark: 'hsl(282, 100%, 16%)',
  glow: 'hsl(280, 100%, 70%)',
  base: 'hsl(270, 100%, 60%)',
  strong: 'hsl(266, 78%, 45%)',
  accent: 'hsl(192, 65%, 72%)',
  accentDark: 'hsl(192, 50%, 35%)',
  accentLight: 'hsl(192, 50%, 90%)',
  destructive: 'hsl(5, 100%, 71%)',
};

export const lightTheme = createTheme(vars, {
  color: {
    background: 'transparent',
    foreground: colorPalette.dark,
    primary: colorPalette.dark,
    primaryForeground: colorPalette.light,
    secondary: colorPalette.light,
    secondaryForeground: colorPalette.dark,
    muted: 'hsl(210 40% 96%)',
    mutedForeground: 'hsl(215.4 16.3% 46.9%)',
    accent: colorPalette.accent,
    accentForeground: colorPalette.dark,
    destructive: colorPalette.destructive,
    destructiveForeground: colorPalette.light,
    border: colorPalette.dark,
    input: colorPalette.dark,
    ring: colorPalette.dark,
    card: 'transparent',
    cardForeground: colorPalette.dark,
    popover: 'transparent',
    popoverForeground: colorPalette.dark,
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
    '4xl': '6rem',
  },
  fontSize: {
    xs: '0.75rem',
    sm: '0.875rem',
    base: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem',
    '5xl': '3rem',
    '6xl': '3.75rem',
    '7xl': '4.5rem',
  },
  radius: {
    none: '0',
    sm: '0.125rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  },
});

export const darkTheme = createTheme(vars, {
  color: {
    background: 'transparent',
    foreground: colorPalette.light,
    primary: colorPalette.light,
    primaryForeground: colorPalette.dark,
    secondary: colorPalette.dark,
    secondaryForeground: colorPalette.light,
    muted: colorPalette.dark,
    mutedForeground: 'hsl(215 20.287% 65.1%)',
    accent: colorPalette.accentDark,
    accentForeground: colorPalette.accentLight,
    destructive: colorPalette.destructive,
    destructiveForeground: colorPalette.accentLight,
    border: colorPalette.accentDark,
    input: 'hsl(217.2 32.6% 17.5%)',
    ring: 'hsl(212.7 26.8% 83.9%)',
    card: 'hsl(222.2 84% 4.9%)',
    cardForeground: 'hsl(210 40% 98%)',
    popover: 'hsl(222.2 84% 4.9%)',
    popoverForeground: 'hsl(210 40% 98%)',
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
    '4xl': '6rem',
  },
  fontSize: {
    xs: '0.75rem',
    sm: '0.875rem',
    base: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem',
    '5xl': '3rem',
    '6xl': '3.75rem',
    '7xl': '4.5rem',
  },
  radius: {
    none: '0',
    sm: '0.125rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  },
});
